"""Report agent: writes the Bid Summary and assembles the final BidRecord."""

import structlog
from pydantic import BaseModel

from rfp.agents.registry import load_registry
from rfp.agents.validator import summarize
from rfp.llm.client import LLMClient, LLMUsage
from rfp.schemas.agents import AddendumChange, BidRecord, FieldResult, FieldValidation, Source

log = structlog.get_logger()

SUMMARY_FIELDS = ("Title", "company_name", "Due Date", "Product")   # sources cited by the summary

SUMMARY_RULES = """Write a concise 3-6 sentence summary of a bid for a sales team, using ONLY the \
extracted fields provided. Cover: who issues it, what is being bought (products, quantities), the \
final due date and how to submit, the contract term, key requirements (bonds, affidavits, \
manufacturer authorization, contract vehicle), and anything changed by addendums. \
Never guess a missing field; simply leave it out."""


class BidSummary(BaseModel):
    summary: str


def _text(value) -> str:
    return "; ".join(value) if isinstance(value, list) else str(value)


class ReportAgent:
    def __init__(self, llm: LLMClient, tier: str = "fast"):
        self.llm = llm
        self.tier = tier

    def summarize(self, bid_id: str, results: dict[str, FieldResult],
                  changes: list[AddendumChange]) -> tuple[FieldResult, LLMUsage]:
        facts = "\n".join(f"- {name}: {_text(r.value)}" for name, r in results.items() if r.value is not None)
        change_text = "\n".join(f"- Addendum {c.addendum_number} changed {c.field}: "
                                f"{_text(c.old_value)} -> {_text(c.new_value)}" for c in changes) or "- none"
        user = f"Bid: {bid_id}\n\nExtracted fields:\n{facts}\n\nAddendum changes:\n{change_text}"
        output, usage = self.llm.structured(agent="report", system=SUMMARY_RULES, user=user,
                                            response_model=BidSummary, tier=self.tier, max_tokens=800)
        sources: list[Source] = []
        for name in SUMMARY_FIELDS:
            for s in results.get(name, FieldResult(value=None, confidence=0)).sources[:1]:
                if s not in sources:
                    sources.append(s)
        return FieldResult(value=output.summary.strip(), sources=sources, confidence=0.8,
                           notes="Generated by the report agent from the validated fields."), usage


def build_record(bid_id: str, results: dict[str, FieldResult], summary: FieldResult | None,
                 changes: list[AddendumChange], validations: dict[str, FieldValidation]) -> BidRecord:
    """All registry fields, in registry order. Missing ones are explicit nulls with a reason."""
    fields: dict[str, FieldResult] = {}
    for spec in load_registry()[1]:
        if spec.generated:
            fields[spec.name] = summary or FieldResult(value=None, confidence=0.0,
                                                       notes="Summary not generated")
        else:
            fields[spec.name] = results.get(spec.name) or FieldResult(
                value=None, confidence=0.0, notes="Not found in documents")
    return BidRecord(bid_id=bid_id, fields=fields, addendum_changes=changes,
                     validation=summarize(validations))